
#ifndef SCALER_SERIAL_RPEDEFINE_H
#define SCALER_SERIAL_RPEDEFINE_H

#define _SUPPORT_FPGA_DATECODE_1206_ABOVE_			1				
#define _FPGA_SUPPORT_1D_DEGAMMA_LUT_				1

#if defined(_SUPPORT_FPGA_DATECODE_1206_ABOVE_) && ( _SUPPORT_FPGA_DATECODE_1206_ABOVE_== 1)
#define _FPGA_SUPPORT_3D_LUT_						1

#define _FPGA_SUPPORT_1D_CCT_LUT_					1
#define _FPGA_SUPPORT_1D_EXTRA_LUT_					0

#define _FPGA_SUPPORT_1D_DEGAMMA_TEST_LUT_			0
#else
#define _FPGA_SUPPORT_3D_LUT_						0

#define _FPGA_SUPPORT_1D_DEGAMMA_TEST_LUT_			1
#define _FPGA_SUPPORT_1D_CCT_LUT_					0

#define _FPGA_SUPPORT_1D_EXTRA_LUT_					0
#endif /* _SUPPORT_FPGA_DATECODE_1206_ABOVE_ */

#endif /* SCALER_SERIAL_RPEDEFINE_H */