//
// Version
//

#define _SCALER_SERIAL_DLL_VERSION_MAJOR 0
#define _SCALER_SERIAL_DLL_VERSION_MINOR 9
#define _SCALER_SERIAL_DLL_VERSION_FLAG 8
#define _SCALER_SERIAL_DLL_VERSION_BUILD 123

#define _SCALER_SERIAL_DLL_VERSION_STRING "0.9.8.123"

